### ISSUE TITLE
Make it compatible with VS 2017 new .csproj format

### ISSUE THREAD

**Issue by eclaus** [golavr/ConfigurationTransform#1]
When used in a VS2017 .csproj (i.e. <Project Sdk="Microsoft.NET.Sdk">), targets must be changed to follow the new syntax, and therefore be correctly executed.

**before** (will not be executed)
<Target Name="AfterCompile" ... >
<Target Name="AfterPublish" ... >

**after** (will be executed)
<Target Name="TransformConfig" AfterTargets="AfterCompile" ... >
<Target Name="CopyTransformedConfig" AfterTargets="AfterPublish" ... >

The new Target names above are just an exemple, it does not matter anymore AFAIK.

**Comment by patricknolan** [comment]
Hi @golavr  I just installed this extension and am using the latest .csproj format. However, when I use "Add Config Transforms" for a config file it corrupts my project file.

Could you advise when this fix\enhancement will be available?

**Comment by golavr** [comment]
Hi @patricknolan you need to remove old configurations from project file prior using the new version since i made some breaking changes in the format.
just open your project file in editor and remove all configuration transformations sections manually.
After removal just apply "Add Config Transforms" on all configs you want to transform.
I working on "Remove old Config Transforms" menu command to handle this removal, it will be part of v3.2 release.

Remove the following sections manually:
<UsingTask ...
<Target Name="AfterCompile" ...
<Target Name="AfterPublish" ...
<Target Name="AfterBuild" ...

**Comment by golavr** [comment]
Fixed in v3.2

**Comment by patricknolan** [comment]
Hi @golavr I just installed v3.2 and when I run "Add Config Transforms" for a config file the project still fails to load with the error 

`error  : The attribute "xmlns" in element <UsingTask> is unrecognized.
`

Should this be working with v3.2 when using the latest cproj file format in 2017?

**Comment by golavr** [comment]
@patricknolan please send me sample of your project i want to look into it.
Make sure you remove older transformation before [Migrating to v3.2 from older versions](https://github.com/golavr/ConfigurationTransform/wiki/Migrating-to-v3.2-from-older-versions).

Please also check if path of <UsingTask TaskName="TransformXml" AssemblyFile="..." in project file is correct.

**Comment by patricknolan** [comment]
Hi @golavr sorry for the slow response. I have attached a sample project which is basically the ASPNet.Core template project.

If I try and "Add Config Transforms" for the web.config it fails.

Should this work?

[TransformExample.zip](https://github.com/golavr/ConfigurationTransform/files/1846347/TransformExample.zip)

**Comment by patricknolan** [comment]
Hi @golavr just checking if you got my previous message?
